import Navbar from "./components/Navbar"
import Footer from "./components/Footer"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <html lang="en">
        <head>
          <link
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
            rel="stylesheet"
          />
        </head>
        <body>
        <Navbar />
          {children}
        <Footer />
        </body>
      </html>
    </>
  )
}
