// app/layout.tsx
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { AuthProvider } from "./context/AuthContext";
import ChatSidebar from "./components/ChatSideBar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
          rel="stylesheet"
        />
      </head>
      <body className="d-flex flex-column min-vh-100" style={{
        margin: "0 auto",    // center content
        fontSize: "0.9rem",  // scale text
        width: "100%",
      }}>
        <AuthProvider>
          <Navbar />

          {/* Content grows between Navbar & Footer */}
          <div className="flex-grow-1 container-fluid">
            <div className="row h-100">
              {/* Sidebar */}
              <div className="col-3 col-md-2 p-0 border-end">
                <ChatSidebar />
              </div>

              {/* Main Chat */}
              <div className="col-9 col-md-10 p-0 d-flex flex-column">
                {children}
              </div>
            </div>
          </div>

          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
